# Generated by Django 2.2.7 on 2019-11-06 01:13

from django.db import migrations, models
import eithers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('issue_a', models.CharField(max_length=50)),
                ('issue_b', models.CharField(max_length=50)),
                ('image_a', models.ImageField(blank=True, upload_to=eithers.models.questions_image_path)),
                ('image_b', models.ImageField(blank=True, upload_to=eithers.models.questions_image_path)),
            ],
        ),
    ]
